###################################################################

# Created by write_sdc on Thu Jan 1 15:34:04 2026

###################################################################
set sdc_version 2.0

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -max_library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -min scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -min_library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c
set_max_area 0
set_load -pin_load 0.5 [get_ports {S[32]}]
set_load -pin_load 0.5 [get_ports {S[31]}]
set_load -pin_load 0.5 [get_ports {S[30]}]
set_load -pin_load 0.5 [get_ports {S[29]}]
set_load -pin_load 0.5 [get_ports {S[28]}]
set_load -pin_load 0.5 [get_ports {S[27]}]
set_load -pin_load 0.5 [get_ports {S[26]}]
set_load -pin_load 0.5 [get_ports {S[25]}]
set_load -pin_load 0.5 [get_ports {S[24]}]
set_load -pin_load 0.5 [get_ports {S[23]}]
set_load -pin_load 0.5 [get_ports {S[22]}]
set_load -pin_load 0.5 [get_ports {S[21]}]
set_load -pin_load 0.5 [get_ports {S[20]}]
set_load -pin_load 0.5 [get_ports {S[19]}]
set_load -pin_load 0.5 [get_ports {S[18]}]
set_load -pin_load 0.5 [get_ports {S[17]}]
set_load -pin_load 0.5 [get_ports {S[16]}]
set_load -pin_load 0.5 [get_ports {S[15]}]
set_load -pin_load 0.5 [get_ports {S[14]}]
set_load -pin_load 0.5 [get_ports {S[13]}]
set_load -pin_load 0.5 [get_ports {S[12]}]
set_load -pin_load 0.5 [get_ports {S[11]}]
set_load -pin_load 0.5 [get_ports {S[10]}]
set_load -pin_load 0.5 [get_ports {S[9]}]
set_load -pin_load 0.5 [get_ports {S[8]}]
set_load -pin_load 0.5 [get_ports {S[7]}]
set_load -pin_load 0.5 [get_ports {S[6]}]
set_load -pin_load 0.5 [get_ports {S[5]}]
set_load -pin_load 0.5 [get_ports {S[4]}]
set_load -pin_load 0.5 [get_ports {S[3]}]
set_load -pin_load 0.5 [get_ports {S[2]}]
set_load -pin_load 0.5 [get_ports {S[1]}]
set_load -pin_load 0.5 [get_ports {S[0]}]
create_clock [get_ports clk]  -name CLK  -period 2.5  -waveform {0 1.25}
set_clock_uncertainty -setup 0.2  [get_clocks CLK]
set_clock_uncertainty -hold 0.3  [get_clocks CLK]
set_clock_transition -max -rise 0.1 [get_clocks CLK]
set_clock_transition -max -fall 0.1 [get_clocks CLK]
set_clock_transition -min -rise 0.1 [get_clocks CLK]
set_clock_transition -min -fall 0.1 [get_clocks CLK]
set_input_delay -clock CLK  0.5  [get_ports {A[31]}]
set_input_delay -clock CLK  0.5  [get_ports {A[30]}]
set_input_delay -clock CLK  0.5  [get_ports {A[29]}]
set_input_delay -clock CLK  0.5  [get_ports {A[28]}]
set_input_delay -clock CLK  0.5  [get_ports {A[27]}]
set_input_delay -clock CLK  0.5  [get_ports {A[26]}]
set_input_delay -clock CLK  0.5  [get_ports {A[25]}]
set_input_delay -clock CLK  0.5  [get_ports {A[24]}]
set_input_delay -clock CLK  0.5  [get_ports {A[23]}]
set_input_delay -clock CLK  0.5  [get_ports {A[22]}]
set_input_delay -clock CLK  0.5  [get_ports {A[21]}]
set_input_delay -clock CLK  0.5  [get_ports {A[20]}]
set_input_delay -clock CLK  0.5  [get_ports {A[19]}]
set_input_delay -clock CLK  0.5  [get_ports {A[18]}]
set_input_delay -clock CLK  0.5  [get_ports {A[17]}]
set_input_delay -clock CLK  0.5  [get_ports {A[16]}]
set_input_delay -clock CLK  0.5  [get_ports {A[15]}]
set_input_delay -clock CLK  0.5  [get_ports {A[14]}]
set_input_delay -clock CLK  0.5  [get_ports {A[13]}]
set_input_delay -clock CLK  0.5  [get_ports {A[12]}]
set_input_delay -clock CLK  0.5  [get_ports {A[11]}]
set_input_delay -clock CLK  0.5  [get_ports {A[10]}]
set_input_delay -clock CLK  0.5  [get_ports {A[9]}]
set_input_delay -clock CLK  0.5  [get_ports {A[8]}]
set_input_delay -clock CLK  0.5  [get_ports {A[7]}]
set_input_delay -clock CLK  0.5  [get_ports {A[6]}]
set_input_delay -clock CLK  0.5  [get_ports {A[5]}]
set_input_delay -clock CLK  0.5  [get_ports {A[4]}]
set_input_delay -clock CLK  0.5  [get_ports {A[3]}]
set_input_delay -clock CLK  0.5  [get_ports {A[2]}]
set_input_delay -clock CLK  0.5  [get_ports {A[1]}]
set_input_delay -clock CLK  0.5  [get_ports {A[0]}]
set_input_delay -clock CLK  0.5  [get_ports {B[31]}]
set_input_delay -clock CLK  0.5  [get_ports {B[30]}]
set_input_delay -clock CLK  0.5  [get_ports {B[29]}]
set_input_delay -clock CLK  0.5  [get_ports {B[28]}]
set_input_delay -clock CLK  0.5  [get_ports {B[27]}]
set_input_delay -clock CLK  0.5  [get_ports {B[26]}]
set_input_delay -clock CLK  0.5  [get_ports {B[25]}]
set_input_delay -clock CLK  0.5  [get_ports {B[24]}]
set_input_delay -clock CLK  0.5  [get_ports {B[23]}]
set_input_delay -clock CLK  0.5  [get_ports {B[22]}]
set_input_delay -clock CLK  0.5  [get_ports {B[21]}]
set_input_delay -clock CLK  0.5  [get_ports {B[20]}]
set_input_delay -clock CLK  0.5  [get_ports {B[19]}]
set_input_delay -clock CLK  0.5  [get_ports {B[18]}]
set_input_delay -clock CLK  0.5  [get_ports {B[17]}]
set_input_delay -clock CLK  0.5  [get_ports {B[16]}]
set_input_delay -clock CLK  0.5  [get_ports {B[15]}]
set_input_delay -clock CLK  0.5  [get_ports {B[14]}]
set_input_delay -clock CLK  0.5  [get_ports {B[13]}]
set_input_delay -clock CLK  0.5  [get_ports {B[12]}]
set_input_delay -clock CLK  0.5  [get_ports {B[11]}]
set_input_delay -clock CLK  0.5  [get_ports {B[10]}]
set_input_delay -clock CLK  0.5  [get_ports {B[9]}]
set_input_delay -clock CLK  0.5  [get_ports {B[8]}]
set_input_delay -clock CLK  0.5  [get_ports {B[7]}]
set_input_delay -clock CLK  0.5  [get_ports {B[6]}]
set_input_delay -clock CLK  0.5  [get_ports {B[5]}]
set_input_delay -clock CLK  0.5  [get_ports {B[4]}]
set_input_delay -clock CLK  0.5  [get_ports {B[3]}]
set_input_delay -clock CLK  0.5  [get_ports {B[2]}]
set_input_delay -clock CLK  0.5  [get_ports {B[1]}]
set_input_delay -clock CLK  0.5  [get_ports {B[0]}]
set_input_delay -clock CLK  0.5  [get_ports Cin]
set_output_delay -clock CLK  0.4  [get_ports {S[32]}]
set_output_delay -clock CLK  0.4  [get_ports {S[31]}]
set_output_delay -clock CLK  0.4  [get_ports {S[30]}]
set_output_delay -clock CLK  0.4  [get_ports {S[29]}]
set_output_delay -clock CLK  0.4  [get_ports {S[28]}]
set_output_delay -clock CLK  0.4  [get_ports {S[27]}]
set_output_delay -clock CLK  0.4  [get_ports {S[26]}]
set_output_delay -clock CLK  0.4  [get_ports {S[25]}]
set_output_delay -clock CLK  0.4  [get_ports {S[24]}]
set_output_delay -clock CLK  0.4  [get_ports {S[23]}]
set_output_delay -clock CLK  0.4  [get_ports {S[22]}]
set_output_delay -clock CLK  0.4  [get_ports {S[21]}]
set_output_delay -clock CLK  0.4  [get_ports {S[20]}]
set_output_delay -clock CLK  0.4  [get_ports {S[19]}]
set_output_delay -clock CLK  0.4  [get_ports {S[18]}]
set_output_delay -clock CLK  0.4  [get_ports {S[17]}]
set_output_delay -clock CLK  0.4  [get_ports {S[16]}]
set_output_delay -clock CLK  0.4  [get_ports {S[15]}]
set_output_delay -clock CLK  0.4  [get_ports {S[14]}]
set_output_delay -clock CLK  0.4  [get_ports {S[13]}]
set_output_delay -clock CLK  0.4  [get_ports {S[12]}]
set_output_delay -clock CLK  0.4  [get_ports {S[11]}]
set_output_delay -clock CLK  0.4  [get_ports {S[10]}]
set_output_delay -clock CLK  0.4  [get_ports {S[9]}]
set_output_delay -clock CLK  0.4  [get_ports {S[8]}]
set_output_delay -clock CLK  0.4  [get_ports {S[7]}]
set_output_delay -clock CLK  0.4  [get_ports {S[6]}]
set_output_delay -clock CLK  0.4  [get_ports {S[5]}]
set_output_delay -clock CLK  0.4  [get_ports {S[4]}]
set_output_delay -clock CLK  0.4  [get_ports {S[3]}]
set_output_delay -clock CLK  0.4  [get_ports {S[2]}]
set_output_delay -clock CLK  0.4  [get_ports {S[1]}]
set_output_delay -clock CLK  0.4  [get_ports {S[0]}]
set_input_transition -max 0.85  [get_ports {A[31]}]
set_input_transition -min 0.85  [get_ports {A[31]}]
set_input_transition -max 0.85  [get_ports {A[30]}]
set_input_transition -min 0.85  [get_ports {A[30]}]
set_input_transition -max 0.85  [get_ports {A[29]}]
set_input_transition -min 0.85  [get_ports {A[29]}]
set_input_transition -max 0.85  [get_ports {A[28]}]
set_input_transition -min 0.85  [get_ports {A[28]}]
set_input_transition -max 0.85  [get_ports {A[27]}]
set_input_transition -min 0.85  [get_ports {A[27]}]
set_input_transition -max 0.85  [get_ports {A[26]}]
set_input_transition -min 0.85  [get_ports {A[26]}]
set_input_transition -max 0.85  [get_ports {A[25]}]
set_input_transition -min 0.85  [get_ports {A[25]}]
set_input_transition -max 0.85  [get_ports {A[24]}]
set_input_transition -min 0.85  [get_ports {A[24]}]
set_input_transition -max 0.85  [get_ports {A[23]}]
set_input_transition -min 0.85  [get_ports {A[23]}]
set_input_transition -max 0.85  [get_ports {A[22]}]
set_input_transition -min 0.85  [get_ports {A[22]}]
set_input_transition -max 0.85  [get_ports {A[21]}]
set_input_transition -min 0.85  [get_ports {A[21]}]
set_input_transition -max 0.85  [get_ports {A[20]}]
set_input_transition -min 0.85  [get_ports {A[20]}]
set_input_transition -max 0.85  [get_ports {A[19]}]
set_input_transition -min 0.85  [get_ports {A[19]}]
set_input_transition -max 0.85  [get_ports {A[18]}]
set_input_transition -min 0.85  [get_ports {A[18]}]
set_input_transition -max 0.85  [get_ports {A[17]}]
set_input_transition -min 0.85  [get_ports {A[17]}]
set_input_transition -max 0.85  [get_ports {A[16]}]
set_input_transition -min 0.85  [get_ports {A[16]}]
set_input_transition -max 0.85  [get_ports {A[15]}]
set_input_transition -min 0.85  [get_ports {A[15]}]
set_input_transition -max 0.85  [get_ports {A[14]}]
set_input_transition -min 0.85  [get_ports {A[14]}]
set_input_transition -max 0.85  [get_ports {A[13]}]
set_input_transition -min 0.85  [get_ports {A[13]}]
set_input_transition -max 0.85  [get_ports {A[12]}]
set_input_transition -min 0.85  [get_ports {A[12]}]
set_input_transition -max 0.85  [get_ports {A[11]}]
set_input_transition -min 0.85  [get_ports {A[11]}]
set_input_transition -max 0.85  [get_ports {A[10]}]
set_input_transition -min 0.85  [get_ports {A[10]}]
set_input_transition -max 0.85  [get_ports {A[9]}]
set_input_transition -min 0.85  [get_ports {A[9]}]
set_input_transition -max 0.85  [get_ports {A[8]}]
set_input_transition -min 0.85  [get_ports {A[8]}]
set_input_transition -max 0.85  [get_ports {A[7]}]
set_input_transition -min 0.85  [get_ports {A[7]}]
set_input_transition -max 0.85  [get_ports {A[6]}]
set_input_transition -min 0.85  [get_ports {A[6]}]
set_input_transition -max 0.85  [get_ports {A[5]}]
set_input_transition -min 0.85  [get_ports {A[5]}]
set_input_transition -max 0.85  [get_ports {A[4]}]
set_input_transition -min 0.85  [get_ports {A[4]}]
set_input_transition -max 0.85  [get_ports {A[3]}]
set_input_transition -min 0.85  [get_ports {A[3]}]
set_input_transition -max 0.85  [get_ports {A[2]}]
set_input_transition -min 0.85  [get_ports {A[2]}]
set_input_transition -max 0.85  [get_ports {A[1]}]
set_input_transition -min 0.85  [get_ports {A[1]}]
set_input_transition -max 0.85  [get_ports {A[0]}]
set_input_transition -min 0.85  [get_ports {A[0]}]
set_input_transition -max 0.85  [get_ports {B[31]}]
set_input_transition -min 0.85  [get_ports {B[31]}]
set_input_transition -max 0.85  [get_ports {B[30]}]
set_input_transition -min 0.85  [get_ports {B[30]}]
set_input_transition -max 0.85  [get_ports {B[29]}]
set_input_transition -min 0.85  [get_ports {B[29]}]
set_input_transition -max 0.85  [get_ports {B[28]}]
set_input_transition -min 0.85  [get_ports {B[28]}]
set_input_transition -max 0.85  [get_ports {B[27]}]
set_input_transition -min 0.85  [get_ports {B[27]}]
set_input_transition -max 0.85  [get_ports {B[26]}]
set_input_transition -min 0.85  [get_ports {B[26]}]
set_input_transition -max 0.85  [get_ports {B[25]}]
set_input_transition -min 0.85  [get_ports {B[25]}]
set_input_transition -max 0.85  [get_ports {B[24]}]
set_input_transition -min 0.85  [get_ports {B[24]}]
set_input_transition -max 0.85  [get_ports {B[23]}]
set_input_transition -min 0.85  [get_ports {B[23]}]
set_input_transition -max 0.85  [get_ports {B[22]}]
set_input_transition -min 0.85  [get_ports {B[22]}]
set_input_transition -max 0.85  [get_ports {B[21]}]
set_input_transition -min 0.85  [get_ports {B[21]}]
set_input_transition -max 0.85  [get_ports {B[20]}]
set_input_transition -min 0.85  [get_ports {B[20]}]
set_input_transition -max 0.85  [get_ports {B[19]}]
set_input_transition -min 0.85  [get_ports {B[19]}]
set_input_transition -max 0.85  [get_ports {B[18]}]
set_input_transition -min 0.85  [get_ports {B[18]}]
set_input_transition -max 0.85  [get_ports {B[17]}]
set_input_transition -min 0.85  [get_ports {B[17]}]
set_input_transition -max 0.85  [get_ports {B[16]}]
set_input_transition -min 0.85  [get_ports {B[16]}]
set_input_transition -max 0.85  [get_ports {B[15]}]
set_input_transition -min 0.85  [get_ports {B[15]}]
set_input_transition -max 0.85  [get_ports {B[14]}]
set_input_transition -min 0.85  [get_ports {B[14]}]
set_input_transition -max 0.85  [get_ports {B[13]}]
set_input_transition -min 0.85  [get_ports {B[13]}]
set_input_transition -max 0.85  [get_ports {B[12]}]
set_input_transition -min 0.85  [get_ports {B[12]}]
set_input_transition -max 0.85  [get_ports {B[11]}]
set_input_transition -min 0.85  [get_ports {B[11]}]
set_input_transition -max 0.85  [get_ports {B[10]}]
set_input_transition -min 0.85  [get_ports {B[10]}]
set_input_transition -max 0.85  [get_ports {B[9]}]
set_input_transition -min 0.85  [get_ports {B[9]}]
set_input_transition -max 0.85  [get_ports {B[8]}]
set_input_transition -min 0.85  [get_ports {B[8]}]
set_input_transition -max 0.85  [get_ports {B[7]}]
set_input_transition -min 0.85  [get_ports {B[7]}]
set_input_transition -max 0.85  [get_ports {B[6]}]
set_input_transition -min 0.85  [get_ports {B[6]}]
set_input_transition -max 0.85  [get_ports {B[5]}]
set_input_transition -min 0.85  [get_ports {B[5]}]
set_input_transition -max 0.85  [get_ports {B[4]}]
set_input_transition -min 0.85  [get_ports {B[4]}]
set_input_transition -max 0.85  [get_ports {B[3]}]
set_input_transition -min 0.85  [get_ports {B[3]}]
set_input_transition -max 0.85  [get_ports {B[2]}]
set_input_transition -min 0.85  [get_ports {B[2]}]
set_input_transition -max 0.85  [get_ports {B[1]}]
set_input_transition -min 0.85  [get_ports {B[1]}]
set_input_transition -max 0.85  [get_ports {B[0]}]
set_input_transition -min 0.85  [get_ports {B[0]}]
set_input_transition -max 0.85  [get_ports Cin]
set_input_transition -min 0.85  [get_ports Cin]
